"""
kiln.nn - a neural network whose every arithmetic operation is machine code
KILN emitted.

Forward, backward and the optimiser step all run on kernels generated by
this project. Nothing here calls a BLAS, a framework, or numpy. The pieces:

  matmul            kiln.gemm          (the 8x8 register-blocked kernel)
  transpose         kiln.transpose     (needed twice per layer in backprop)
  bias + relu       a two-level loop emitted below, because the general map
                    kernel is one-dimensional and a bias broadcasts across
                    rows
  relu backward     a fused map: dZ = dY * step(Y)
  loss and dY       a fused reduce and a fused map
  SGD with momentum a fused map, updating velocity and weights in one pass

The point of the exercise is falsifiability. tests/verify_training.py runs
the identical network - same initial weights, same data, same hyperparameters
- in float64 numpy, and compares the loss curves step by step. If any kernel
were subtly wrong, the curves would separate.

Pure standard library.
"""

import math
import struct

from . import gemm, ir, isa, jit, transpose
from .asm import Asm
from .lower import Schedule
from .runtime import compile as kcompile


# ------------------------------------------------------- bias + activation

def build_bias_act(B, D, relu=True, unroll=4):
    """void f(float *Y, const float *bias) for Y[B][D].

    Y[i][j] = max(Y[i][j] + bias[j], 0). The bias pointer rewinds every row,
    which is exactly the broadcast a one-dimensional map cannot express.
    """
    if D % 4:
        raise ValueError("bias_act needs D divisible by 4")
    U = unroll
    while U > 1 and (D // 4) % U:
        U -= 1
    vecs = D // 4
    blocks = vecs // U
    left = vecs - blocks * U

    a = Asm(f"bias_act_{B}x{D}")
    if relu:
        a(isa.MOVI_zero(31))
    a.mov_imm(4, B)                     # row counter
    a.label("row")
    a(isa.MOV_reg(5, 0))                # Y cursor for this row
    a(isa.MOV_reg(6, 1))                # bias cursor, rewound every row
    if blocks:
        a.mov_imm(7, blocks)
        a.label("col")
        for u in range(U):
            a(isa.LDR_q(u, 5, u * 16))
            a(isa.LDR_q(8 + u, 6, u * 16))
        for u in range(U):
            a(isa.FADD(u, u, 8 + u))
            if relu:
                a(isa.FMAX(u, u, 31))
            a(isa.STR_q(u, 5, u * 16))
        a(isa.ADD_imm(5, 5, U * 16))
        a(isa.ADD_imm(6, 6, U * 16))
        a(isa.SUBS_imm(7, 7, 1))
        a.bcond("ne", "col")
    for u in range(left):
        a(isa.LDR_q(u, 5, u * 16))
        a(isa.LDR_q(8 + u, 6, u * 16))
        a(isa.FADD(u, u, 8 + u))
        if relu:
            a(isa.FMAX(u, u, 31))
        a(isa.STR_q(u, 5, u * 16))
    a(isa.ADD_imm(0, 0, D * 4)) if D * 4 <= 4095 else None
    if D * 4 > 4095:
        a.mov_imm(9, D * 4)
        a(isa.ADD_reg(0, 0, 9))
    a(isa.SUBS_imm(4, 4, 1))
    a.bcond("ne", "row")
    a(isa.RET())
    return a


class BiasAct:
    def __init__(self, B, D, relu=True):
        self.asm = build_bias_act(B, D, relu)
        self.code = jit.load(self.asm)
        self.fn = self.code.fn(None, [jit.VOIDP, jit.VOIDP])

    def __call__(self, Y, bias):
        self.fn(Y.ptr, bias.ptr)


# -------------------------------------------------------- fused map helpers

class Fused:
    """A one-dimensional KILN program with a fixed set of buffers."""

    def __init__(self, name, build, n, sched=None):
        p = ir.Program(name)
        build(p, n)
        ir.contract_program(p)
        self.prog = p
        self.c = kcompile(p, sched or Schedule(6), contract=False)
        self.n = n

    def bind(self, **bufs):
        self.c.bind(bufs)
        return self

    def __call__(self):
        return self.c.run()


def relu_backward(n):
    def build(p, n):
        p.map([("dz", ir.load("dy") * ir.step(ir.load("y")))], n)
    return Fused("relu_bwd", build, n)


def mse_and_grad(n, scale):
    """One pass computes the loss; a second writes the gradient."""
    def build_loss(p, n):
        d = ir.load("y") - ir.load("t")
        p.reduce("loss", "sum", d * d, n)
    def build_grad(p, n):
        p.map([("dy", (ir.load("y") - ir.load("t")) * ir.f32(scale))], n)
    return Fused("mse", build_loss, n), Fused("mse_grad", build_grad, n)


def sgd_step(n, lr, momentum, wd):
    """v = momentum*v - lr*(g + wd*w) ; w = w + v, in one pass over memory."""
    def build(p, n):
        g, w, v = ir.load("g"), ir.load("w"), ir.load("v")
        nv = v * ir.f32(momentum) - (g + w * ir.f32(wd)) * ir.f32(lr)
        p.map([("v", nv)], n)
    def build2(p, n):
        p.map([("w", ir.load("w") + ir.load("v"))], n)
    return Fused("sgd_v", build, n), Fused("sgd_w", build2, n)


# ------------------------------------------------------------------ layers

class Linear:
    def __init__(self, B, din, dout, relu=True, seed=0):
        if din % 4 or dout % 8 or B % 8:
            raise ValueError(f"Linear needs B%8, din%4, dout%8; "
                             f"got {B},{din},{dout}")
        self.B, self.din, self.dout, self.relu = B, din, dout, relu

        self.W = jit.Buf(din * dout)
        self.b = jit.Buf(dout)
        self.Wt = jit.Buf(dout * din)
        self.dW = jit.Buf(din * dout)
        self.db = jit.Buf(dout)
        self.vW = jit.Buf(din * dout)
        self.vb = jit.Buf(dout)

        self.X = None
        self.Xt = jit.Buf(din * B)
        self.Y = jit.Buf(B * dout)
        self.dX = jit.Buf(B * din)
        self.dZ = jit.Buf(B * dout)

        # He initialisation, from a reproducible generator so the numpy
        # reference can be started from exactly the same weights
        rnd = _lcg(seed)
        s = math.sqrt(2.0 / din)
        for i in range(din * dout):
            self.W[i] = ir.f32(rnd() * s)

        self.fwd = gemm.gemm(B, dout, din)          # Y   = X  @ W
        self.bwd_x = gemm.gemm(B, din, dout)        # dX  = dZ @ W^T
        self.bwd_w = gemm.gemm(din, dout, B)        # dW  = X^T @ dZ
        self.ones = jit.Buf(8 * B, 1.0)
        self.bwd_b = gemm.gemm(8, dout, B)          # db  = 1^T @ dZ
        self.db_mat = jit.Buf(8 * dout)
        self.tr_w = transpose.transpose(din, dout)
        self.tr_x = transpose.transpose(B, din)

        self.bias_act = BiasAct(B, dout, relu)
        self.act_bwd = relu_backward(B * dout) if relu else None
        if relu:
            self.act_bwd.bind(dy=jit.Buf(1), y=self.Y, dz=self.dZ)

    def forward(self, X):
        self.X = X
        self.fwd(X, self.W, self.Y)
        self.bias_act(self.Y, self.b)
        return self.Y

    def backward(self, dY):
        if self.relu:
            self.act_bwd.c.bind({"dy": dY, "y": self.Y, "dz": self.dZ})
            self.act_bwd()
            dZ = self.dZ
        else:
            dZ = dY
        self.tr_w(self.W, self.Wt)              # W^T for dX
        self.bwd_x(dZ, self.Wt, self.dX)
        self.tr_x(self.X, self.Xt)              # X^T for dW
        self.bwd_w(self.Xt, dZ, self.dW)
        self.bwd_b(self.ones, dZ, self.db_mat)  # column sums of dZ
        for j in range(self.dout):
            self.db[j] = self.db_mat[j]
        return self.dX

    def params(self):
        return [(self.W, self.dW, self.vW), (self.b, self.db, self.vb)]


def _lcg(seed):
    """A tiny reproducible normal generator, so KILN and the numpy reference
    can start from bit-identical weights."""
    state = [seed * 2654435761 % (1 << 32) or 12345]

    def u():
        state[0] = (1664525 * state[0] + 1013904223) % (1 << 32)
        return (state[0] + 0.5) / (1 << 32)

    def normal():
        a, b = u(), u()
        return math.sqrt(-2.0 * math.log(a)) * math.cos(2 * math.pi * b)

    return normal


class MLP:
    def __init__(self, B, dims, seed=0):
        self.B = B
        self.layers = []
        for i in range(len(dims) - 1):
            self.layers.append(Linear(B, dims[i], dims[i + 1],
                                      relu=(i < len(dims) - 2),
                                      seed=seed + i * 17 + 1))
        self.n_out = B * dims[-1]
        self.loss_k, self.grad_k = mse_and_grad(self.n_out, 2.0 / self.n_out)
        self.dY = jit.Buf(self.n_out)
        self._opt = {}

    def forward(self, X):
        h = X
        for l in self.layers:
            h = l.forward(h)
        return h

    def loss(self, Y, T):
        self.loss_k.c.bind({"y": Y, "t": T})
        s = self.loss_k()["loss"]
        return s / self.n_out

    def backward(self, Y, T):
        self.grad_k.c.bind({"y": Y, "t": T, "dy": self.dY})
        self.grad_k()
        g = self.dY
        for l in reversed(self.layers):
            g = l.backward(g)

    def step(self, lr=0.05, momentum=0.9, wd=0.0):
        for l in self.layers:
            for w, g, v in l.params():
                n = len(w)
                key = (n, lr, momentum, wd)
                ks = self._opt.get(key)
                if ks is None:
                    ks = self._opt[key] = sgd_step(n, lr, momentum, wd)
                kv, kw = ks
                kv.c.bind({"g": g, "w": w, "v": v})
                kv()
                kw.c.bind({"w": w, "v": v})
                kw()

    def n_params(self):
        return sum(len(l.W) + len(l.b) for l in self.layers)

    def flops_per_step(self):
        """Forward is one multiply per layer; backward is two."""
        f = 0
        for l in self.layers:
            f += 2 * l.B * l.din * l.dout * 3
        return f
